export const ALL_ABOUT_REQUEST = "ALL_ABOUT_REQUEST";
export const ALL_ABOUT_SUCCESS = "ALL_ABOUT_SUCCESS";
export const ALL_ABOUT_FAIL = "ALL_ABOUT_FAIL";

export const ABOUT_DETAILS_REQUEST = "ABOUT_DETAILS_REQUEST";
export const ABOUT_DETAILS_SUCCESS = "ABOUT_DETAILS_SUCCESS";
export const ABOUT_DETAILS_FAIL = "ABOUT_DETAILS_FAIL";

export const NEW_ABOUT_REQUEST = "NEW_ABOUT_REQUEST";
export const NEW_ABOUT_SUCCESS = "NEW_ABOUT_SUCCESS";
export const NEW_ABOUT_RESET = "NEW_ABOUT_RESET";
export const NEW_ABOUT_FAIL = "NEW_ABOUT_FAIL";

export const ADMIN_ABOUT_REQUEST = "ADMIN_ABOUT_REQUEST";
export const ADMIN_ABOUT_SUCCESS = "ADMIN_ABOUT_SUCCESS";
export const ADMIN_ABOUT_FAIL = "ADMIN_ABOUT_FAIL";

export const DELETE_ABOUT_REQUEST = "DELETE_ABOUT_REQUEST";
export const DELETE_ABOUT_SUCCESS = "DELETE_ABOUT_SUCCESS";
export const DELETE_ABOUT_RESET = "DELETE_ABOUT_RESET";
export const DELETE_ABOUT_FAIL = "DELETE_ABOUT_FAIL";

export const UPDATE_ABOUT_REQUEST = "UPDATE_ABOUT_REQUEST";
export const UPDATE_ABOUT_SUCCESS = "UPDATE_ABOUT_SUCCESS";
export const UPDATE_ABOUT_FAIL = "UPDATE_ABOUT_FAIL";
export const UPDATE_ABOUT_RESET = "UPDATE_ABOUT_RESET";


export const CLEAR_ERRORS = "CLEAR_ERRORS";