export const ALL_HOME_REQUEST = "ALL_HOME_REQUEST";
export const ALL_HOME_SUCCESS = "ALL_HOME_SUCCESS";
export const ALL_HOME_FAIL = "ALL_HOME_FAIL";

export const HOME_DETAILS_REQUEST = "HOME_DETAILS_REQUEST";
export const HOME_DETAILS_SUCCESS = "HOME_DETAILS_SUCCESS";
export const HOME_DETAILS_FAIL = "HOME_DETAILS_FAIL";

export const NEW_HOME_REQUEST = "NEW_HOME_REQUEST";
export const NEW_HOME_SUCCESS = "NEW_HOME_SUCCESS";
export const NEW_HOME_RESET = "NEW_HOME_RESET";
export const NEW_HOME_FAIL = "NEW_HOME_FAIL";

export const ADMIN_HOME_REQUEST = "ADMIN_HOME_REQUEST";
export const ADMIN_HOME_SUCCESS = "ADMIN_HOME_SUCCESS";
export const ADMIN_HOME_FAIL = "ADMIN_HOME_FAIL";

export const DELETE_HOME_REQUEST = "DELETE_HOME_REQUEST";
export const DELETE_HOME_SUCCESS = "DELETE_HOME_SUCCESS";
export const DELETE_HOME_RESET = "DELETE_HOME_RESET";
export const DELETE_HOME_FAIL = "DELETE_HOME_FAIL";

export const UPDATE_HOME_REQUEST = "UPDATE_HOME_REQUEST";
export const UPDATE_HOME_SUCCESS = "UPDATE_HOME_SUCCESS";
export const UPDATE_HOME_FAIL = "UPDATE_HOME_FAIL";
export const UPDATE_HOME_RESET = "UPDATE_HOME_RESET";


export const CLEAR_ERRORS = "CLEAR_ERRORS";