export const ALL_PIN_REQUEST = "ALL_PIN_REQUEST";
export const ALL_PIN_SUCCESS = "ALL_PIN_SUCCESS";
export const ALL_PIN_FAIL = "ALL_PIN_FAIL";

export const PIN_DETAILS_REQUEST = "PIN_DETAILS_REQUEST";
export const PIN_DETAILS_SUCCESS = "PIN_DETAILS_SUCCESS";
export const PIN_DETAILS_FAIL = "PIN_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";