export const ALL_PIN_REQUEST = "ALL_PIN_REQUEST";
export const ALL_PIN_SUCCESS = "ALL_PIN_SUCCESS";
export const ALL_PIN_FAIL = "ALL_PIN_FAIL";

export const PIN_DETAILS_REQUEST = "PIN_DETAILS_REQUEST";
export const PIN_DETAILS_SUCCESS = "PIN_DETAILS_SUCCESS";
export const PIN_DETAILS_FAIL = "PIN_DETAILS_FAIL";

export const ADMIN_PIN_REQUEST = "ADMIN_PIN_REQUEST";
export const ADMIN_PIN_SUCCESS = "ADMIN_PIN_SUCCESS";
export const ADMIN_PIN_FAIL = "ADMIN_PIN_FAIL";

export const NEW_PIN_REQUEST = "NEW_PIN_REQUEST";
export const NEW_PIN_SUCCESS = "NEW_PIN_SUCCESS";
export const NEW_PIN_RESET = "NEW_PIN_RESET";
export const NEW_PIN_FAIL = "NEW_PIN_FAIL";

export const UPDATE_PIN_REQUEST = "UPDATE_PIN_REQUEST";
export const UPDATE_PIN_SUCCESS = "UPDATE_PIN_SUCCESS";
export const UPDATE_PIN_RESET = "UPDATE_PIN_RESET";
export const UPDATE_PIN_FAIL = "UPDATE_PIN_FAIL";

export const DELETE_PIN_REQUEST = "DELETE_PIN_REQUEST";
export const DELETE_PIN_SUCCESS = "DELETE_PIN_SUCCESS";
export const DELETE_PIN_RESET = "DELETE_PIN_RESET";
export const DELETE_PIN_FAIL = "DELETE_PIN_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";